// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadResult() {
  return window['go']['main']['App']['DownloadResult']();
}

export function StitchImages(arg1, arg2) {
  return window['go']['main']['App']['StitchImages'](arg1, arg2);
}

export function UploadImages(arg1) {
  return window['go']['main']['App']['UploadImages'](arg1);
}
