// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadResult():Promise<Record<string, any>>;

export function StitchImages(arg1:Array<string>,arg2:string):Promise<Record<string, any>>;

export function UploadImages(arg1:Array<string>):Promise<Record<string, any>>;
